class uniform
{
	name = "Uniform";
	icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
	items[]=
	{
		//SOG
		"vn_b_uniform_macv_01_17",
		"vn_b_uniform_macv_02_17",
		"vn_b_uniform_macv_04_17",
		"vn_b_uniform_macv_06_17",
		"vn_b_uniform_aus_01_01",
		"vn_b_uniform_aus_08_01",
		"vn_b_uniform_macv_01_03",
		"vn_b_uniform_macv_01_15",
		"vn_b_uniform_macv_01_06",
		"vn_b_uniform_macv_01_08",
		"vn_b_uniform_macv_01_01",
		"vn_b_uniform_macv_01_05",
		"vn_b_uniform_macv_02_02",
		"vn_b_uniform_macv_03_07",
		"vn_b_uniform_macv_04_05",
		"vn_b_uniform_macv_04_02",
		"vn_b_uniform_macv_06_07",
		"vn_b_uniform_macv_01_16",
		"vn_b_uniform_macv_03_16",
		"vn_b_uniform_macv_06_16",
		"vn_b_uniform_macv_01_18",
		"vn_b_uniform_macv_03_18",
		"vn_b_uniform_macv_06_18",
		"vn_b_uniform_sas_03_06",
		"vn_b_uniform_k2b_02_05",
		"vn_b_uniform_k2b_01_01",
		"vn_b_uniform_k2b_02_01",
		"vn_b_uniform_seal_01_06",
		"vn_b_uniform_seal_01_02",
		"vn_b_uniform_seal_02_07",
		"vn_b_uniform_seal_03_01",
		"vn_b_uniform_seal_05_06",
		"vn_b_uniform_seal_05_02",
		"vn_b_uniform_seal_07_02",
		"vn_b_uniform_seal_07_04",
		"vn_b_uniform_seal_09_01",
		/////
		"U_B_CBRN_Suit_01_Wdl_F",
		"U_B_CombatUniform_mcam",
		"U_B_CombatUniform_mcam_wdl_f",
		"U_C_Uniform_Farmer_01_F",
		"U_C_HunterBody_grn",
		"U_O_PilotCoveralls",
		"U_C_IDAP_Man_cargo_F",
		"U_C_ConstructionCoverall_Black_F",
		"U_C_ConstructionCoverall_Red_F",

		"rhs_uniform_acu_ocp",
		"rhs_uniform_acu_oefcp",
		"rhs_uniform_cossack",
		"rhs_uniform_vdv_emr",
		"rhs_uniform_vdv_flora",
		"rhs_uniform_FROG01_wd",
		"rhs_uniform_g3_blk",
		"rhs_uniform_g3_m81",
		"rhs_uniform_g3_rgr",
		"rhs_uniform_gorka_r_g",
		"rhs_uniform_vdv_mflora",
		"rhsgref_uniform_altis_lizard",
		"rhsgref_uniform_woodland"
	};
};
class vest
{
	name = "Vest";
	icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
	items[]=
	{
		//SOG light
		"vn_b_vest_anzac_10",
		"vn_b_vest_anzac_04",
		"vn_b_vest_anzac_06",
		"vn_b_vest_anzac_05",
		"vn_b_vest_anzac_01",
		"vn_b_vest_anzac_03",
		"vn_b_vest_usarmy_10",
		"vn_b_vest_usarmy_05",
		"vn_b_vest_usarmy_08",
		"vn_b_vest_usarmy_07",
		"vn_b_vest_usarmy_06",
		"vn_b_vest_usarmy_03",
		"vn_b_vest_usarmy_01",
		"vn_b_vest_sas_04",
		"vn_b_vest_sas_01",
		//SOG better
		"vn_b_vest_aircrew_01",
		"vn_b_vest_anzac_09",
		"vn_b_vest_anzac_08",
		"vn_b_vest_usarmy_13",
		"vn_b_vest_usarmy_14",
		"vn_b_vest_aircrew_03",
		"vn_b_vest_seal_01",
		"vn_b_vest_seal_07",
		"vn_b_vest_seal_06",
		"vn_b_vest_seal_02",
		"vn_b_vest_usmc_05",
		"vn_b_vest_usmc_04",
		"vn_b_vest_usmc_03",
		"vn_b_vest_usmc_01",
		/////
		"V_Chestrig_rgr",
		"V_SmershVest_01_F",
		"V_HarnessOGL_brn",
		"V_HarnessO_brn",
		"V_TacChestrig_grn_F",
		"V_PlateCarrierGL_rgr",
		"V_PlateCarrier1_rgr_noflag_F",
		"V_PlateCarrier2_rgr_noflag_F",
		"V_PlateCarrierSpec_rgr",
		"V_EOD_olive_F",
		"V_PlateCarrierIAGL_oli",
		"V_PlateCarrierIA1_dgtl",

		"rhs_6sh117_mg",
		"rhs_6sh117_grn",
		"rhs_6b13_Flora_6sh92_vog",
		"rhs_6b13_EMR_6sh92_vog",
		"rhs_6b23_6sh116_vog_od",
		"rhs_6b23_6sh92_vog",
		"rhs_6b3_VOG_2",
		"rhsusf_mbav_rifleman",
		"rhsusf_iotv_ucp_Rifleman",
		"rhsusf_iotv_ocp_Rifleman",
		"rhsusf_plateframe_rifleman",
		"rhsusf_spc_patchless_radio",
		"rhsusf_spcs_ocp_teamleader",
		"rhsusf_spcs_ucp_teamleader",
		"rhsgref_alice_webbing",
		"rhsgref_chicom",
		"rhsgref_6b23_ttsko_mountain_rifleman"
	};
};
class helmet
{
	name = "Helmet";
	icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
	items[]=
	{
		//SOG
		"vn_i_beret_03_03",
		"vn_i_beret_01_01",
		"vn_i_beret_03_01",
		"vn_i_helmet_m1_02_01",
		"vn_i_helmet_m1_01_02",
		"vn_i_helmet_m1_02_02",
		"vn_b_bandana_03",
		"vn_b_bandana_06",
		"vn_b_bandana_07",
		"vn_b_bandana_05",
		"vn_b_boonie_01_08",
		"vn_b_boonie_01_01",
		"vn_b_boonie_01_07",
		"vn_b_boonie_01_05",
		"vn_b_helmet_aph6_02_02",
		"vn_b_helmet_aph6_02_05",
		"vn_b_helmet_aph6_02_03",
		"vn_b_helmet_aph6_02_04",
		"vn_b_helmet_aph6_02_01",
		"vn_b_helmet_m1_01_02",
		"vn_b_helmet_m1_14_01",
		"vn_b_helmet_m1_06_01",
		"vn_b_helmet_m1_11_01",
		"vn_b_helmet_m1_08_02",
		"vn_b_helmet_m1_09_02",
		"vn_b_helmet_svh4_02_01",
		"vn_b_helmet_svh4_02_04",
		"vn_b_helmet_svh4_02_02",
		"vn_b_helmet_svh4_02_05",
		"vn_b_helmet_svh4_02_03",
		"vn_b_helmet_t56_02_01",
		"vn_b_helmet_t56_01_02",
		"vn_b_helmet_sog_01",
		"vn_b_helmet_t56_02_03",
		/////
		"H_HelmetB_camo",
		"H_HelmetB_snakeskin",
		"H_HelmetSpecB",
		"H_HelmetSpecB_paint1",
		"H_PilotHelmetHeli_B",
		"H_PilotHelmetHeli_O",
		"H_PilotHelmetFighter_O",
		"H_PilotHelmetFighter_B",
		"H_HelmetSpecB_wdl",
		"H_HelmetHBK_F",

		"rhsusf_ihadss",
		"rhs_6b26_green",
		"rhs_6b26",
		"rhs_6b28_green",
		"rhs_6b48",
		"rhsusf_ach_bare",
		"rhsusf_ach_bare_wood",
		"rhsusf_ach_helmet_M81",
		"rhsusf_cvc_green_helmet",
		"rhsusf_opscore_fg",
		"rhsusf_opscore_mc_cover_pelt_cam",
		"rhs_zsh7a_alt",
		"rhs_altyn_visordown",
		"rhsgref_helmet_M1_bare",
		"rhsgref_helmet_m1940"
	};
	special[]=
	{
		"rhsusf_ihadss"
	};
};
class backpack
{
	name = "BackPack";
	icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
	items[]=
	{
		//SOG
		"vn_b_pack_pfield_01",
		"vn_b_pack_p08_01",
		"vn_b_pack_p44_01",
		"vn_b_pack_lw_04",
		"vn_b_pack_m5_01",
		"vn_b_pack_lw_07",
		"vn_b_pack_lw_05",
		"vn_b_pack_lw_02",
		"vn_b_pack_lw_01",
		"vn_b_pack_lw_06",
		"vn_b_pack_trp_03_02",
		"vn_b_pack_trp_01_02",
		"vn_b_pack_trp_04_02",
		"vn_b_pack_trp_02_02",
		"vn_b_pack_arvn_01",
		"vn_b_pack_arvn_02",
		"vn_b_pack_arvn_03",
		"vn_b_pack_arvn_04",
		"vn_b_pack_05_02",
		"vn_b_pack_02_02",
		"vn_b_pack_03_02",
		"vn_b_pack_04_02",
		"vn_b_pack_01_02",
		"vn_b_pack_seal_01",
		"vn_b_pack_05",
		"vn_b_pack_02",
		"vn_b_pack_03",
		"vn_b_pack_04",
		"vn_b_pack_01",
		"vn_b_pack_trp_03",
		"vn_b_pack_trp_01",
		"vn_b_pack_trp_04",
		"vn_b_pack_trp_02",
		"vn_b_pack_m41_01",
		"vn_b_pack_m41_02",
		"vn_b_pack_m41_03",
		"vn_b_pack_m41_04",
		"vn_b_pack_m41_05",
		/////
		//SOG Parachute
		"vn_b_pack_ba18_01",
		"vn_b_pack_ba22_01",
		"vn_b_pack_t10_01",
		/////
		"ACE_TacticalLadder_Pack",
		"B_RadioBag_01_wdl_F",

		"B_AssaultPack_eaf_F",
		"B_AssaultPack_rgr",
		"B_AssaultPack_wdl_F",
		"B_AssaultPack_mcamo",
		"B_Carryall_khk",
		"B_Carryall_oli",
		"B_Carryall_wdl_F",
		"B_Kitbag_rgr",
		"B_ViperHarness_oli_F",
		"B_ViperHarness_ghex_F",
		
		"rhsgref_wdl_alicepack",
		"rhs_sidor"

		/*"AOR2_Backpack_Kitbag",
		"CADPAT_Backpack_Kitbag",
		"DualTex_Backpack_Kitbag",
		"M81_Backpack_Kitbag",
		"M90_Backpack_Kitbag",
		"MarPat_Backpack_Kitbag",
		"MC_Backpack_Kitbag",
		"Tiger_Backpack_Kitbag",
		"SURPAT_Backpack_Kitbag",*/
	};
};